IF NOT EXISTS(SELECT * FROM [DBO].[STATUS] WHERE NAME = 'Not Started')
INSERT INTO [DBO].[STATUS](NAME, ORDINAL) VALUES('Not Started', 0);
IF NOT EXISTS(SELECT * FROM [DBO].[STATUS] WHERE NAME = 'In Progress')
INSERT INTO [DBO].[STATUS](NAME, ORDINAL) VALUES('In Progress', 1);
IF NOT EXISTS(SELECT * FROM [DBO].[STATUS] WHERE NAME = 'Completed')
INSERT INTO [DBO].[STATUS](NAME, ORDINAL) VALUES('Completed', 2);