DECLARE @statusId int,
		@taskId int,
		@userId int

IF NOT EXISTS (SELECT * FROM [USER] WHERE USERNAME = 'bhogg')
	INSERT INTO [DBO].[USER] ([FIRSTNAME], [LASTNAME], [USERNAME])
	VALUES (N'Boss', N'Hogg', N'bhogg')

IF NOT EXISTS (SELECT * FROM [USER] WHERE USERNAME = 'jbob')
	INSERT INTO [DBO].[USER] ([FIRSTNAME], [LASTNAME], [USERNAME])
	VALUES (N'Jim', N'Bob', N'jbob')

IF NOT EXISTS (SELECT * FROM [USER] WHERE USERNAME = 'jdoe')
	INSERT INTO [DBO].[USER] ([FIRSTNAME], [LASTNAME], [USERNAME])
	VALUES (N'John', N'Doe', N'jdoe')

IF NOT EXISTS(SELECT * FROM DBO.TASK WHERE SUBJECT = 'Test Task')
BEGIN
	SELECT TOP 1 @statusId = STATUSID FROM STATUS ORDER BY STATUSID;
	SELECT TOP 1 @userId = USERID FROM [USER] ORDER BY USERID;

	INSERT INTO DBO.TASK(SUBJECT, STARTDATE, STATUSID, CREATEDDATE, CREATEDUSERID)
		VALUES('Test Task', GETDATE(), @STATUSID, GETDATE(), @USERID);

	SET @taskId = SCOPE_IDENTITY();

	INSERT [dbo].[TaskUser] ([TaskId],[UserId])
		VALUES (@taskId, @userId)
END